server:
  port: 5000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
          - Path=/api/v1/customers/**

        - id: product-service
          uri: lb:http://products-service
          predicates:
          - Path=/api/v1/products/**, /api/v1/categories/**

        - id: order-service
          uri: lb:http://order-service
          predicates:
          - Path=/api/v1/orders/**